#!/bin/bash

# Linux Layer 2 setup for VXLAN bridging
# Create virtual bridge br0
ip link add br0 type bridge               
# Bring up the bridge interface
ip link set dev br0 up                   
# Create VXLAN tunnel interface with ID 10
ip link add vxlan10 type vxlan id 10 dstport 4789  
# Bring up VXLAN interface
ip link set vxlan10 up                   
# Add VXLAN to bridge
brctl addif br0 vxlan10                  
# Add eth2 to the bridge (Layer 2 connectivity)
brctl addif br0 eth2                     
# Bring up eth2
ip link set eth2 up                      

# FRRouting configuration
vtysh << EOF
conf t

# Set router hostname
hostname mannahri-router-3
# Disable IPv6 forwarding
no ipv6 forwarding                       

interface eth1
 # IP address for connection to Router1
 ip address 10.1.1.6/30                  
 # Enable OSPF on this interface
 ip ospf area 0                          

interface lo
 # Loopback IP used for BGP
 ip address 1.1.1.3/32                   
 # Advertise loopback in OSPF
 ip ospf area 0                          

router bgp 1
 # BGP peer with Router1 in same AS
 neighbor 1.1.1.1 remote-as 1            
 # Use loopback as source for BGP session
 neighbor 1.1.1.1 update-source lo       
 address-family l2vpn evpn
  # Activate EVPN for this peer
  neighbor 1.1.1.1 activate              
  # Advertise all local VNI
  advertise-all-vni                      
 exit-address-family

# Start OSPF process (details per-interface)
router ospf                              

EOF
