#!/bin/bash


# Linux Layer 2 setup for VXLAN bridging

# Creates a new Linux bridge called br0
ip link add br0 type bridge                  
# Brings the bridge interface up
ip link set dev br0 up                       
# Creates VXLAN interface with VNI 10 using UDP port 4789
ip link add vxlan10 type vxlan id 10 dstport 4789   
# Brings the VXLAN interface up
ip link set dev vxlan10 up                   
# Adds VXLAN interface to the bridge
brctl addif br0 vxlan10                      
# Adds physical interface eth0 to the bridge
brctl addif br0 eth0                         
# Brings up eth0 interface
ip link set eth0 up                          

vtysh << EOF
conf t
# Sets router hostname
hostname mannahri-router-4                   
# Disables IPv6
no ipv6 forwarding                           

interface eth2                               
 # Assigns this interface an IP in the P2P /30 subnet
 ip address 10.1.1.10/30                     
 # Adds interface to OSPF Area 0
 ip ospf area 0                              

interface lo
 # Loopback IP used for BGP peering
 ip address 1.1.1.4/32                       
 # Loopback is advertised in OSPF too
 ip ospf area 0                              

# Starts BGP in AS 1
router bgp 1                                 
 # Peers with Route Reflector (Router1)
 neighbor 1.1.1.1 remote-as 1                
 # Use loopback interface as BGP source IP
 neighbor 1.1.1.1 update-source lo           
 address-family l2vpn evpn
  # Activates EVPN neighbor
  neighbor 1.1.1.1 activate                  
  # Advertises all VNI routes
  advertise-all-vni                          
 exit-address-family

# Starts OSPF config block (though empty here)
router ospf                                  
EOF
